all:
	node ../Build/main.js Zion.sln build config=release all

release:
	node ../Build/main.js Zion.sln build config=release all

clean:
	node ../Build/main.js Zion.sln clean config=release all

